language: rust
dist: trusty
sudo: false

script:
  - cargo update
  - cargo build --no-default-features --features=$FEATURE
  - cargo test --no-default-features --features=$FEATURE

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUST_BACKTRACE=1

jobs:
  include:
    - env: FEATURE=static
      addons:
        apt:
          packages:
            - cmake
            - gfortran
    - env: FEATURE=intel-mkl

cache: cargo

