language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

deploy:
  - provider: script
    script: cargo test -v
    on:
      all_branches: true
  - provider: script
    script: cargo test -v -- --ignored
    on:
      branch: master

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran
