language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

matrix:
  allow-failures:
    - rust: nightly

script:
  - cargo test

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran
