[package]
name = "ndarray-odeint"
version = "0.6.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "solve ODE using rust-ndarray"
documentation = "https://docs.rs/ndarray-odeint/"
repository = "https://github.com/termoshtt/ndarray-odeint"
keywords = ["ndarray", "ode"]
license = "MIT"

[dependencies]
ndarray = "0.9"
ndarray-linalg = "0.5.4"
num-traits = "0.1"
num-complex = "0.1"
derive-new = "0.4"
