[package]
name = "ndarray-odeint"
version = "0.2.2"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "solve ODE using rust-ndarray"
documentation = "https://docs.rs/ndarray-odeint/"
repository = "https://github.com/termoshtt/ndarray-odeint"
keywords = ["ndarray", "ode"]
license = "MIT"

[dependencies]
ndarray = "0.7.3"
ndarray-linalg = "0.2.1"
itertools = "0.5.7"
num-traits = "0.1.35"
num-complex = "0.1.36"
num-extra = { git = "http://github.com/termoshtt/num-extra", rev = "aefcd7ec18f31d9f70d6c807913d91ac2087b0bf" }

[dev-dependencies]
num-traits = "0.1.35"
ndarray-numtest = "0.1.4"
