[package]
name = "eom"
version = "0.8.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Configurable ODE/PDE solver"
documentation = "https://docs.rs/eom/"
repository = "https://github.com/termoshtt/eom"
keywords = ["ndarray", "ode", "pde"]
categories    = ["algorithms", "science"]
license = "MIT"
readme = "README.md"

[dependencies]
ndarray = "0.10"
ndarray-linalg = "0.6"
num-traits = "0.1"
num-complex = "0.1"
derive-new = "0.4"
