[package]
name = "ndarray-odeint"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
ndarray = "0.7"
itertools = "*"

[dev-dependencies]
num-traits = "*"
ndarray-linalg = "*"
