version: 2.0

references:
  rust_cfg: &rust_cfg
    docker:
      - image: rust:1.32

jobs:
  test-static:
    <<: *rust_cfg
    steps:
      - checkout
      - run:
          name: Test OpenBLAS/FFTW backend
          command: |
            apt update && apt install -y gfortran
            cargo test --no-default-features --features=static

  test-intel-mkl:
    <<: *rust_cfg
    steps:
      - checkout
      - run:
          name: Test Intel MKL backend
          command: |
            cargo test --no-default-features --features=intel-mkl

workflows:
  version: 2
  tests:
    jobs:
      - test-static
      - test-intel-mkl
